server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aicogniblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

app:
  jwt:
    secret: AICogniBlogSecretKey2025AICogniBlogSecretKey2025AICogniBlog
    expiration: 86400000   # 24 小时（毫秒）
  ai:
    api-url: https://api.deepseek.com/v1/chat/completions
    api-key: your-deepseek-api-key-here
    model: deepseek-chat

rsa:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuGvz+4e2kLcUFDLhmt0taRI1WviZkJALHEIjXSIOxmawHBxhO7S5eXcdHvD5QOSRtQfCI2ahBn5bDeVYCH3D8G5txIDyKPnhvCRcJ5wwFP13TNqZaCBbRnpBbDZe7IQtXrcqO+7aphFwaMjrEZqzKQxvbSvWsqSaFBLzpKJ6mpqnApyH+0udYaWJ/9B8XwTXT8I7spo0Rc0s1Yh5eOFPlWyf5OspUeWPCJ9ZrvpIhFEqBXeIUuaafVRsn95Y705OoUYzna7awdrUu76Igsw/AvwnE0RsQvIbSy6JQkYVDEKuUf8m00g7q0+IMIQUVArrpAshplCuIeXksZ8K7dYy6wIDAQAB
  private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC4a/P7h7aQtxQUMuGa3S1pEjVa+JmQkAscQiNdIg7GZrAcHGE7tLl5dx0e8PlA5JG1B8IjZqEGflsN5VgIfcPwbm3EgPIo+eG8JFwnnDAU/XdM2ploIFtGekFsNl7shC1etyo77tqmEXBoyOsRmrMpDG9tK9aypJoUEvOkonqamqcCnIf7S51hpYn/0HxfBNdPwjuymjRFzSzViHl44U+VbJ/k6ylR5Y8In1mu+kiEUSoFd4hS5pp9VGyf3ljvTk6hRjOdrtrB2tS7voiCzD8C/CcTRGxC8htLLolCRhUMQq5R/ybTSDurT4gwhBRUCuukCyGmUK4h5eSxnwrt1jLrAgMBAAECggEACDUBqBVrifgjxBxZjt896JmfVzuN9fF7FRhaY4gi+TBTsQSQTSxnPqEO4jQeG4WweEpumM2158iSu8UTjFkwcZAwgVitriYkpg9GLJsWRrDa8MgfoJMkDLhfFfY7djIRpM/o6L7h6xcGlhsu3tswEukTQlv7k3qgwrjvL8ntQ9j/suExtq/hF7H8C5NrhnfF8w/sGkyHyCHq36nCH5JO6pYBTL0JqHLo1an4qeVA7qhvPq/KajpUFX9PoKZx4QYija5ZV0GXtX5XgwKI+clgwnp70MCJpeCxUhevQMrFQPcntj0+myU6yd5IZJcW25n7u0UdTFxf0gRSLEGP1eCEXQKBgQDVBw6EHJliAdMokTLj0ud32VOsVtYeE/2l04R9XF5sHOzge+7cA63j7VSnuJei+x+Q5jpCo1kaIPRGVvZO+8xInf4Ulg7i4+ampgDTKaNtgWGlvH6FFkdrE+V9VC6uZaJ2vrSwwIsENpLZ7BgyzAVWtld/ubiFJmDoxDsWnJtTJQKBgQDdn6mGXCocKcnjmWjgk+aQUxz1EmrEX2SdeLi8OZ18YvTwdKyQ8D8xOPos57Cmr0zntxbnrPEk6b+u6YfrzX/dvVUcNjI086yN0XJlwC2N4xoP/7YzJwTntaOZ/46NsNDfofQPE8NSqHmYurOkjcj8nTll1+hqbex0s2/4wWCYzwKBgBWv8jpg7vybUvP+VD/9aLM63NnevU2ym1AWiJZ6oOJAz5zLATZE6Z8aulOY51cgWcZWqfe+yYNvd27xy4GfAN0juIo//KP8r66nl83nn0u2sEo/NmI2Mm8kR2jK+TWoAzIzmBGmiICVTb4B2zTQsHpzddT7A14K2jLYR2u15dpBAoGBAInMlY6qTbCXNyWiJHjG3WxNkUq8OdCB88CJ6Gt4c3h82wmLsiSojNIhOESlhswNYYcN61r/yCyIfpvWLqIqc1+/MmVJOWx9OoQvf67OkESRuYnLGFGz6DPeV6wQH2XwU99JBsQ9KIyDnp+dLseZNSgE5kRxu9w5HvXtACkuq843AoGBAMU8kYELZ4WA7jAaakuxsHIJsTPg1odTGMo7Cg0me/UfkYaZlyEDo8cg42G9U75vO0hDvXef+ytH9oJV9Vj8Mpg3spmVdAvcg9CXJt9VwGuoxWzqjNY+oYO7JpeBxLVKa2Q+ytIgjMq2ImM61fP/kBhmrOCJkS2UBbLZPfLNc+Q1

logging:
  level:
    com.aicogniblog: debug
